site_name: Elevate

nav:
    - Elevate: index.md
    - Policy: Policy.md
    - Speakers: Speakers.md
    - Events : 
           Apply: apply.md
           Communicate : communicate.md
           Manage: manage.md
           Think : think.md
           Innovate : innovate.md




               

